version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant:0.114.4
    volumes:
      - /home/pi/projects/bfhome/homeassistant:/config
    environment:
      - TZ=Europe/Moscow
    restart: always
    network_mode: host

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.12
    volumes:
      - /home/pi/projects/bfhome/mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
