version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant:0.114.4
    volumes:
      - /home/pi/projects/bfhome/homeassistant:/config
    environment:
      - TZ=Europe/Moscow
    restart: always
    network_mode: host

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.12
    volumes:
      - /home/pi/projects/bfhome/mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:2.4.0
    volumes:
      - ./home/pi/projects/bfhome/nginx-proxy-manager/config.json:/app/config/production.json
      - ./home/pi/projects/bfhome/nginx-proxy-manager/data:/data
      - ./home/pi/projects/bfhome/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    ports:
      - "8181:8181"
      - "8080:8080"
      - "4443:4443"
    restart: always

  db:
    container_name: mariadb
    image: 'yobasystems/alpine-mariadb:10.4.13'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - /home/pi/projects/bfhome/mariadb/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
