version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant:0114.4
    volumes:
      - /PATH_TO_YOUR_CONFIG:/config
    environment:
      - TZ=Europe/Moscow
    restart: always
    network_mode: host

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.12
    volumes:
      - ./mosquitto_data/:/mosquitto/data/
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
