# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

google_assistant:
  project_id: hsapp-a740b
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  expose_by_default: false
  entity_config:
    switch.mqtt_bedroom_table_light:
      name: свет над столом
      aliases:
        - свет в спальне
      expose: true
      room: спальня
    switch.mqtt_bedroom_bed_light:
      name: свет над кроватью
      aliases:
        - свет в спальне
      expose: true
      room: спальня
    switch.mqtt_kitchen_light:
      name: свет на кухне
      expose: true
      room: кухня
    switch.mqtt_entrance_light:
      name: свет в прихожей
      expose: true
      room: прихожая
    switch.mqtt_bathroom_light:
      name: свет в ванной
      expose: true
      room: ванная
    switch.mqtt_bathroom_fan:
      name: вытяжка в ванной
      expose: true
      room: ванная

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: homeassistant
  password: password
  protocol: 3.1

switch 1:
  - platform: mqtt
    name: "MQTT Bedroom bed light"
    state_topic: "/house/switchConfirm1/"
    command_topic: "/house/switch1/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true

switch 2:
  - platform: mqtt
    name: "MQTT Bedroom table light"
    state_topic: "/house/switchConfirm2/"
    command_topic: "/house/switch2/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true

switch 3:
  - platform: mqtt
    name: "MQTT Kitchen light"
    state_topic: "/house/switchConfirm3/"
    command_topic: "/house/switch3/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true

switch 4:
  - platform: mqtt
    name: "MQTT Entrance light"
    state_topic: "/house/switchConfirm4/"
    command_topic: "/house/switch4/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true

switch 5:
  - platform: mqtt
    name: "MQTT Bathroom light"
    state_topic: "/house/switchConfirm5/"
    command_topic: "/house/switch5/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true

switch 6:
  - platform: mqtt
    name: "MQTT Bathroom fan"
    state_topic: "/house/switchConfirm6/"
    command_topic: "/house/switch6/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true
